### ISSUE TITLE
Extensions can't recognize TS3Hook?

### ISSUE THREAD

**Issue by o305** [exp111/TS3PatchExtensions#12]
Hello,

I have problem with these Extensions because the Extensions can't recognize TS3Hook I think,

Because If I try to use "Custom badges" module and take the badges what I want then confirm it ts3hook console will not type the command,

I mean If I try to use badges manually with ts3hook I need to type `~cmdclientupdate~sclient_badges="Badges"`

and console will type the command in console with "Pink color",

so yeah I think the Extensions can't recognize ts3hook,

I tried to use another versions of Teamspeak, ts3hook and TS3PatchExtensions and didn't work with me.

Could you please explain why I can't use these Extensions.

Thanks.

**Comment by o305** [comment]
I know how to use "customBadges" with python version,

but I mean where can I find TS3 Patch plugin?

**Comment by exp111** [comment]
Well my plugin has like no other features really...

It was released on GitHub but was taken down by TeamSpeak. No idea where you can get the most recent version. Ask the TeaSpeak developer (he wrote it. it's now called TeaConnect I think)

**Comment by o305** [comment]
I saw TS3Patch in GitLab: http://git.mcgalaxy.de:8090/WolverinDEV/TS3-Patch

But I can't build it.

**Comment by exp111** [comment]
Well I don‘t know if I can upload the plugin but you can join the teaspeak server or mine (macoga) and ask for the plugin…
