### ISSUE TITLE
Useless question

### ISSUE THREAD

**Issue by Disgame** [exp111/TS3PatchExtensions#13]
Well I don‘t know if I can upload the plugin but you can join the teaspeak server or mine (macoga) and ask for the plugin…

_Originally posted by @exp111 in https://github.com/exp111/TS3PatchExtensions/issues/12#issuecomment-451778805_

Whats is the teaspeak ip for your server?

**Comment by Bluscream** [comment]
ts3server://ts.teaspeak.de

ts3server://macoga

**Comment by Disgame** [comment]
Thanks
