### ISSUE TITLE
Allow for blockcommands to set a replace command

### ISSUE THREAD

**Issue by Bluscream** [exp111/TS3PatchExtensions#2]
Like `clientupdate` so the server doesn't reply "not implemented"

**Comment by exp111** [comment]
Replace the whole command? Like turn „clientupdate client_badges=…“ into „someothercommand args“?

**Comment by Bluscream** [comment]
No actual just turn the "" empty command that gets send when you block something into "clientupdate" for example

**Comment by exp111** [comment]
Does it get sent? I thought the patch would not send it if you have canceled enabled

**Comment by Bluscream** [comment]
Yeah sadly it cant just drop a packer because then the server would miss the packet with that number

**Comment by Bluscream** [comment]
Implemented with 7eac968a613d8f0bae4df483edf2eb1435c6f82d
