### ISSUE TITLE
connectionInfoSpoofer Setting

### ISSUE THREAD

**Issue by Chazotu** [exp111/TS3PatchExtensions#4]
The connectionInfoSpoofer does not save the below settings when your restart teamspeak

- Block setConnectionInfo

- Block ConnectionInfiAutoUpdate

**Comment by exp111** [comment]
Do you have a connectionInfoSpoofer folder in config/plugins/?
I don't create a config cause it's optional (and I was to lazy to create a directory)

**Comment by Chazotu** [comment]
I did not , just created it now it works fine.
