### ISSUE TITLE
HWID spoofer Config UI

### ISSUE THREAD

**Issue by Chazotu** [exp111/TS3PatchExtensions#7]
Make an Simple Config UI where you can

 - generate a new hwid
- display the current faked hwid

Also an Option to use a different hwid for each connection

**Comment by exp111** [comment]
Do we need that? It currently generates a new HWID every time we connect on a server. As it has no disadvantages having a new hwid we can keep doing that I guess...

**Comment by Bluscream** [comment]
Generating a new one seems useless but what you can do is you can print the last generated hwid to the current tab when the config button of the plugin is clicked

**Comment by Chazotu** [comment]
Blues idear sounds good we could do it like this

**Comment by Chazotu** [comment]
The Last HWID which now gets printed to the chat is the same on every server i am connected , it only changes when i restart the ts3 client. Should it not be a different for each connection ?

* From abouth TeaSpeak checks the hwid

**Comment by exp111** [comment]
It changes if you connect to a new server. But i probably should set a seed.
